In [12]:
import numpy as np
import numpy

In [13]:
def compute_max(event_ids, values):
    max_values = numpy.zeros(numpy.amax(event_ids)+1)
    for i in range(len(event_ids)):
        if values[i] > max_values[event_ids[i]]:
            max_values[event_ids[i]] = values[i]
    max_values[max_values == 0] = numpy.nan
    return max_values

In [21]:
compute_max([78, 78],[1, 3])

array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,   3.])

In [14]:
compute_max([0, 1, 1, 1, 2, 2], [0.4, 0.5, 0.1, 0.2, 0.7, 0.98])

array([ 0.4 ,  0.5 ,  0.98])

In [25]:
compute_max(np.array([0, 0, 0, 7, 1, 7, 7]),np.array([1, 2, 3, 8, 5, 6, 7]))

array([  3.,   5.,  nan,  nan,  nan,  nan,  nan,   8.])

In [26]:
compute_max([0, 1 ,1],[1, -3, -4])  # expected list of nonnegative elements (probabilities)

array([  1.,  nan])

In [28]:
compute_max( [0, 0, 0, 0, 0, 0] , [ 0.99500233,  0.98623795,  0.99329707,  0.99321405,  0.9949128 , 0.99088875] )

array([ 0.99500233])